'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('Games', [
      {
        idCatogory : 1,
        Name: 'Basketball',
        UrlImage :"/images/Basketball.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Racing',
        UrlImage :"/images/Basketball1.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Tennis',
        UrlImage :"/images/Basketball2.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Nintendo Switch',
        UrlImage :"/images/Basketball3.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Baseball',
        UrlImage :"/images/Basketball4.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Mario Golf',
        UrlImage :"/images/Basketball5.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'FIFA',
        UrlImage :"/images/Basketball6.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'GTA',
        UrlImage :"/images/Basketball7.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Taxi & Police',
        UrlImage :"/images/Basketball8.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'AU',
        UrlImage :"/images/Basketball9.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Futsal',
        UrlImage :"/images/Basketball10.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Car',
        UrlImage :"/images/Basketball11.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'GAME & HOBBY',
        UrlImage :"/images/Basketball12.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        idCatogory : 1,
        Name: 'Badmiton',
        UrlImage :"/images/Basketball13.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball14.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball15.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball16.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball17.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball18.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball19.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball20.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball21.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball22.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball23.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball24.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball25.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball26.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball27.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball28.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball29.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball30.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball31.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball32.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball33.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball34.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball35.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball36.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball37.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball38.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball39.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball40.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball41.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball42.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball43.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball44.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball45.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball46.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball47.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball48.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   idCatogory : 12,
      //   Name: 'Basketball',
      //   UrlImage :"/images/Basketball49.jpg",
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
    ]);
  },

  async down (queryInterface, Sequelize) {
    //return queryInterface.bulkDelete('Category', null, {});
  }
};
